### PR TITLE
Documentation initial commit

### PR DESCRIPTION
**Pull request by ecaruyer**

### CODE REVIEW

**Comment by astamm** [comment]
Thanks for the PR @ecaruyer. Why not committing the modified files? Is it related to the fact the @ElentirNimaj, @Florent2305 and myself are in the process of changing the file tree structure of the codebase?

**Comment by ecaruyer** [comment]
Yes ! The idea was to wait for the reorganization of the code to complete, to avoid multiple conflicts to be resolved. In the meantime, we could propose a list of executable+description here in this README?

**Comment by astamm** [comment]
Good for me! I ping @MariePoirierGit so she is aware of this!

**Comment by ecaruyer** [comment]
Good for me too, I shamelessly auto-merge :smile:

**Pull request merged**
